version: '3'

networks:
  laravel:

services:
  nginx: 
    image: nginx:stable-alpine
    container_name: nginx_laravel
    ports: 
      - "7000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel
  
  php:
    image: joao159159/php-laravel-extensions:1.0
    container_name: php_laravel
    volumes: 
      - ./src:/var/www/html
    ports: 
      - "9004:9004"
    networks: 
      - laravel
  
  composer:
    image: composer:latest
    container_name: composer_laravel
    volumes: 
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on: 
      - php
    networks: 
      - laravel
      
  artisan:
    image: joao159159/php-laravel-extensions:1.0
    container_name: artisan_laravel
    volumes: 
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks: 
      - laravel
